import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import `ChakraProvider` component
import { ChakraProvider } from '@chakra-ui/react'
import { MyContextProvider  } from "./context/context"


import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chakra Custom Component",
  description: "Generated by Chakra Custom Component",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MyContextProvider >
          <ChakraProvider>{children}</ChakraProvider>
        </MyContextProvider >
      </body>
    </html>
  );
}
